version: '3.1'

services:
  app:
    build: .
    restart: always
    container_name: ruby_site
    # command: tail -F anything
    command: ruby index.rb
    ports:
        - "8000:8000"
    volumes:
        - ./app:/app
